name: contacts_example

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  firebase_core: ^3.3.0
  permission_handler: ^11.3.1
  contacts_service: ^0.6.3
  cloud_firestore: ^5.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/